version: '3.3'
services:
  db:
    image: mysql:5.5
    container_name: mysql-5.5
    restart: always
    environment:
      MYSQL_USER: IMServer
      MYSQL_PASSWORD: Hellotalk*IMServer
      MYSQL_ROOT_PASSWORD: 65535
    ports:
      - "3306:3306"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./conf.d:/etc/mysql/conf.d
      - ./log:/var/log/mysql